InterviewTaskAE/InterviewTaskAE.Web/Models/ErrorViewModel.cs
using System;

namespace InterviewTaskAE.Web.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

InterviewTaskAE/InterviewTaskAE.Web/Controllers/ArtworksController.cs
using DinkToPdf;
using DinkToPdf.Contracts;
using InterviewTaskAE.Services.Contracts;
using InterviewTaskAE.Web.Utility;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.IO;
using System.Threading.Tasks;

namespace InterviewTaskAE.Web.Controllers
{
    public class ArtworksController : Controller
    {
        private readonly ILogger<ArtworksController> _logger;
        private readonly IArticAPIService _apiService;
        private readonly IConverter _converter;

        public ArtworksController(ILogger<ArtworksController> logger, IArticAPIService apiService, IConverter converter)
        {
            _converter = converter;
            _logger = logger;
            _apiService = apiService;
        }

        public async Task<IActionResult> Index(int page)
        {
            try
            {
                var artworks = await _apiService.ExtractArtworksAsync(page);
                return View(artworks);
            }
            catch (Exception)
            {
                return View("Error");
            }
        }

        public async Task<IActionResult> Details(int id)
        {
            try
            {
                var artwork = await _apiService.ExtractArtworkByIdAsync(id);
                return View(artwork);
            }
            catch (Exception)
            {
                return View("Error");
            }
        }

        public async Task<IActionResult> Search(string search, int page)
        {
            try
            {
                ViewBag.Search = search;
                var artworks = await _apiService.SearchArtworksAsync(search, page);
                artworks.Pagination.SearchCriteria = search;
                return View(artworks);
            }
            catch (Exception)
            {
                return View("Error");
            }
        }

        public async Task<IActionResult> CreatePdf(int id)
        {
            try
            {
                var artwork = await _apiService.ExtractArtworkByIdAsync(id);

                var globalSettings = new GlobalSettings
                {
                    ColorMode = ColorMode.Color,
                    Orientation = Orientation.Portrait,
                    PaperSize = PaperKind.A4,
                    Margins = new MarginSettings { Top = 10 },
                    DocumentTitle = "PDF Report"
                };
                var objectSettings = new ObjectSettings
                {
                    PagesCount = true,
                    HtmlContent = TemplateGenerator.GetHTMLString(artwork),
                    WebSettings = { DefaultEncoding = "utf-8", UserStyleSheet = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot/css", "styles.css") }
                };

                var pdf = new HtmlToPdfDocument
                {
                    GlobalSettings = globalSettings,
                    Objects = { objectSettings }
                };

                var file = _converter.Convert(pdf);

                return File(file, "application/pdf", "PDFReport.pdf");
            }
            catch (Exception)
            {
                return View("Error");
            }
        }
    }
}

InterviewTaskAE/InterviewTaskAE.Web/Controllers/HomeController.cs
using InterviewTaskAE.Services.Contracts;
using InterviewTaskAE.Web.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System.Diagnostics;

namespace InterviewTaskAE.Web.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;
        private readonly IArticAPIService _apiService;
        public HomeController(ILogger<HomeController> logger, IArticAPIService apiService)
        {
            _logger = logger;
            _apiService = apiService;
        }

        public IActionResult Index()
        {        
            return View();
        }

        public IActionResult Privacy()
        {
         
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

InterviewTaskAE/InterviewTaskAE.Web/Views/Artworks/Details.cshtml
@model InterviewTaskAE.Models.Artwork

<section class="section mt-5">
    <div class="container d-flex h-100 flex-column">
        <div class="row h-100 justify-content-center align-items-center">
            <div class="row">
                <div class="col-md-5">
                    <div>
                        <img alt="Picture" class="img-fluid" src="@Model.Url" />
                    </div>
                </div>
                <div class="col-md-7 d-flex mt-2">
                    <div>
                        <div class="container">
                            <dl class="row">
                                <dt class="col-sm-2">
                                    Title
                                </dt>
                                <dd class="col-sm-10">
                                    @Html.DisplayFor(model => model.Name)
                                </dd>
                                <dt class="col-sm-2">
                                    Artist
                                </dt>
                                <dd class="col-sm-10">
                                    @Html.DisplayFor(model => model.Artist.Name)
                                </dd>
                                <dt class="col-sm-2">
                                    Description
                                </dt>
                                <dd class="col-sm-10">
                                    @Html.DisplayFor(model => model.Description)
                                </dd>
                                <dt class="col-sm-2">
                                    Origin
                                </dt>
                                <dd class="col-sm-10">
                                    @Html.DisplayFor(model => model.PlaceOfOrigin)
                                </dd>
                                <dt class="col-sm-2">
                                    Created
                                </dt>
                                <dd class="col-sm-10">
                                    @Html.DisplayFor(model => model.AssumedDate)
                                </dd>
                                <dt class="col-sm-2">
                                    Dimensions
                                </dt>
                                <dd class="col-sm-10">
                                    @Html.DisplayFor(model => model.Dimensions)
                                </dd>
                                <dt class="col-sm-2">
                                    Medium
                                </dt>
                                <dd class="col-sm-10">
                                    @Html.DisplayFor(model => model.Medium)
                                </dd>
                            </dl>
                        </div>

                        <div class="row m-md-1">
                            <div>
                                <a class="btn btn-secondary btn-sm" asp-controller="Artworks" asp-action="CreatePdf" asp-route-id="@Model.ApiId">Download Pdf</a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

</section>

InterviewTaskAE/InterviewTaskAE.Web/Views/Artworks/Index.cshtml
@model InterviewTaskAE.Services.Models.ListingModel

<form asp-action="Search" method="get">
    <div class="form-actions no-color">
        <p>
            @Html.TextBox("search", ViewBag.Search as string)
            <input type="submit" value="Search" class="btn btn-primary btn-sm" />
        </p>
    </div>
</form>

<div class="row">
    @foreach (var item in Model.Artworks)
    {
        <div class="col-sm-4">
            <div class="card" style="width: 18rem;">
                <img src="@item.Url" class="card-img-top" alt="image-not-available" width="200" height="300">
                <div class="card-body">
                    <h4 class="card-title"><b>@item.Name</b></h4>
                    <h4 class="card-title"> @item.Artist.Name</h4>
                    <h4 class="card-title"> @item.AssumedDate</h4>
                    <a class="btn btn-primary btn-sm" asp-controller="Artworks" asp-action="Details" asp-route-id="@item.ApiId">View artwork</a>
                </div>
            </div>
        </div>}
</div>

@if (Model.Pagination.CurrentPage > 1)
{
    <input type="button" value="Previous Page" onclick="@("window.location.href='" + @Url.Action("Index", "Artworks", new { page = Model.Pagination.CurrentPage - 1 }) + "'");" />
}

@if (Model.Pagination.CurrentPage < Model.Pagination.TotalPages)
{
    <input type="button" value="Next Page" onclick="@("window.location.href='" + @Url.Action("Index", "Artworks", new { page = Model.Pagination.CurrentPage + 1 }) + "'");" />
}

InterviewTaskAE/InterviewTaskAE.Web/Views/Artworks/Search.cshtml
@model InterviewTaskAE.Services.Models.ListingModel

<div class="row">
    @foreach (var item in Model.Artworks)
    {
        <div class="col-sm-4">
            <div class="card" style="width: 18rem;">
                <img src="@item.Url" class="card-img-top" alt="image-not-available" width="200" height="300">
                <div class="card-body">
                    <h1 class="card-title"><b>@item.Name</b></h1>
                    <h4 class="card-title"> @item.Artist.Name</h4>
                    <h4 class="card-title"> @item.AssumedDate</h4>
                    <a class="btn btn-primary btn-sm" asp-controller="Artworks" asp-action="Details" asp-route-id="@item.ApiId">View artwork</a>
                </div>
            </div>
        </div>}
</div>

@if (Model.Pagination.CurrentPage > 1)
{
    <input type="button" value="Previous Page" onclick="@("window.location.href='" + @Url.Action("Search", "Artworks", new { search = Model.Pagination.SearchCriteria, page = Model.Pagination.CurrentPage - 1 }) + "'");" />
}

@if (Model.Pagination.CurrentPage < Model.Pagination.TotalPages)
{
    <input type="button" value="Next Page" onclick="@("window.location.href='" + @Url.Action("Search", "Artworks", new { search = Model.Pagination.SearchCriteria, page = Model.Pagination.CurrentPage + 1 }) + "'");" />
}

InterviewTaskAE/InterviewTaskAE.Web/Views/Home/Index.cshtml
@model ICollection<InterviewTaskAE.Models.Artwork>
@{
    ViewData["Title"] = "Home Page";
}

<style>
body { background-image: url('https://img.theculturetrip.com/1440x807/smart/wp-content/uploads/2019/05/feature_j87t9a.jpg'); background-repeat: no-repeat; background-attachment: fixed; background-size: cover; }
</style>

<div class="text-center">
    <a class="button1" onclick="window.location.href='Artworks/Index'">Explore our Artworks</a>
</div>

InterviewTaskAE/InterviewTaskAE.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - InterviewTaskAE.Web</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <img src="~/images/artic.png" width="42" height="42" />
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">

                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>                    
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>